apiVersion: batch/v1
kind: Job
metadata:
  name: download-kimi-k2
  namespace: nim-llm
spec:
  activeDeadlineSeconds: 86400
  backoffLimit: 6
  template:
    metadata:
      labels:
        job-name: download-kimi-k2
    spec:
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: kimi-k2
      containers:
        - name: kimi-k2-downloader
          image: docker.io/library/python:3.10-slim
          command:
            - bash
            - '-c'
          args:
            - |
              set -e
              echo "Starting model download at $(date)"

              # Install to a writable directory
              mkdir -p /tmp/pip-local
              pip install --target=/tmp/pip-local huggingface_hub --no-cache-dir
              export PYTHONPATH=/tmp/pip-local:$PYTHONPATH

              mkdir -p /models/kimi-k2
              python - <<'EOF'
              import os
              import sys
              import time
              sys.path.insert(0, '/tmp/pip-local')
              from huggingface_hub import snapshot_download

              token = os.getenv("HF_TOKEN")
              print(f"Starting download of Kimi-K2-Thinking at {time.ctime()}")
              print("Downloading Kimi-K2-Thinking model - this may take some time")

              snapshot_download(
                  repo_id="moonshotai/Kimi-K2-Thinking",
                  local_dir="/models/kimi-k2",
                  token=token,
                  resume_download=True,
                  local_dir_use_symlinks=False
              )

              print(f"Download completed successfully at {time.ctime()}")
              EOF
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token-secret
                  key: token
            - name: PYTHONUSERBASE
              value: /tmp/pip-local
            - name: PATH
              value: '/tmp/pip-local/bin:/usr/local/bin:/usr/bin:/bin'
            - name: HF_HUB_DISABLE_XET_WARNING
              value: '1'
            - name: HF_HUB_DISABLE_SYMLINKS_WARNING
              value: '1'
            - name: HF_HUB_ENABLE_HF_TRANSFER
              value: '0'
            - name: HF_HUB_DOWNLOAD_TIMEOUT
              value: '3600'
            - name: HF_HOME
              value: /tmp/hf-cache
          resources:
            limits:
              cpu: '4'
              memory: 32Gi
            requests:
              cpu: '2'
              memory: 8Gi
          volumeMounts:
            - name: model-storage
              mountPath: /models
          securityContext:
            runAsUser: 1000890000
            runAsGroup: 1000890000
      restartPolicy: OnFailure
      securityContext:
        runAsUser: 1000890000
        runAsGroup: 1000890000
        fsGroup: 1000890000
